version: '3.8'

services:
  django:
    container_name: django
    build:
      context: ./app_server
      dockerfile: Dockerfile
    command: sh -c "gunicorn app_server.wsgi:application --bind 0.0.0.0:8000 & daphne -b 0.0.0.0 -p 8001 app_server.asgi:application -v 0"
    volumes:
      - ./app_server:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
      - 8001
    env_file:
      - env.prod
    environment:
      - DJANGO_SETTINGS_MODULE=app_server.settings
    depends_on:
      - db
    
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - django
    ports:
      - 8443:8443
    volumes:
      - ./nginx/certs:/etc/nginx/ssl
      - static_volume:/usr/src/app/staticfiles

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
 
  db:
    image: postgres:15
    container_name: db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - env.prod

volumes:
  postgres_data:
  static_volume: