services:
  django:
    container_name: django
    networks:
      - pong_network
    build:
      context: ./app_server
      dockerfile: Dockerfile
    volumes:
      - ./app_server:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
      - ./app_server/media:/usr/src/app/media
    init: true
    expose:
      - 8000
      - 8001
    env_file:
      - env.prod
    environment:
      - LOCAL_IP=${LOCAL_IP}
      - LOCAL_IP_CSRF=${LOCAL_IP_CSRF}
    depends_on:
      - postgres
    restart: always
    
  nginx:
    container_name: nginx
    networks:
      - pong_network
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - django
    init: true
    ports:
      - 8443:8443
    volumes:
      - ./nginx/certs:/etc/nginx/ssl
      - static_volume:/usr/src/app/staticfiles
      - ./app_server/media:/usr/src/app/media
    restart: always

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    networks:
      - pong_network
    container_name: redis
    ports:
      - "6380:6379"
    restart: always
 
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres
    networks:
      - pong_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - env.prod
    restart: always

volumes:
  postgres_data:
  static_volume:

networks:
  pong_network:
    driver: bridge