# Generated by Django 5.0.3 on 2024-04-11 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('tournament_id', models.CharField(default='NONE', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchName', models.CharField(default='', max_length=200)),
                ('gameType', models.CharField(default='', max_length=100)),
                ('gameDuration', models.IntegerField(default=0)),
                ('matchDate', models.CharField(default='')),
                ('matchTime', models.CharField(default='')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pong_online.tournaments')),
            ],
        ),
        migrations.CreateModel(
            name='UserGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('ballHits', models.IntegerField(default=0)),
                ('ballMisses', models.IntegerField(default=0)),
                ('highestStreak', models.IntegerField(default=0)),
                ('longestBallRallyHits', models.IntegerField(default=0)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pong_online.games')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
