# Generated by Django 5.0.3 on 2024-04-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_online', '0002_alter_usergamestats_game_alter_usergamestats_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='data',
            field=models.JSONField(default={}),
        ),
    ]
