version: '3.8'

services:
  django:
    container_name: django
    build:
      context: ./dnginx
      dockerfile: Dockerfile
    command: sh -c "gunicorn dnginx.wsgi:application --bind 0.0.0.0:8000 --log-level debug & daphne -b 0.0.0.0 -p 8001 dnginx.asgi:application -v 0"
    volumes:
      - ./dnginx:/usr/src/app
    expose:
      - 8000
      - 8001
    env_file:
      - env.prod
    depends_on:
      - db
    
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - django
    ports:
      - 8443:8443
    volumes:
      - ./nginx/certs:/etc/nginx/ssl

  db:
    image: postgres:15
    container_name: db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - env.prod

volumes:
  postgres_data: