# Generated by Django 5.0.3 on 2024-03-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_profile_avatar_profile_last_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_activity',
        ),
    ]
