# Generated by Django 5.0.3 on 2024-05-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0003_remove_profile_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images'),
        ),
    ]
