# Generated by Django 5.0.3 on 2024-03-18 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email_pk', models.TextField(primary_key=True, serialize=False)),
                ('isOnline', models.BooleanField(default=False)),
                ('isSearchingGame', models.BooleanField(default=False)),
                ('name', models.TextField()),
                ('inGameWith', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='pong.users')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('ballHits', models.IntegerField(default=0)),
                ('ballMisses', models.IntegerField(default=0)),
                ('highestStreak', models.IntegerField(default=0)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pong.users')),
            ],
        ),
    ]
