# Generated by Django 5.0.3 on 2024-03-15 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameType', models.TextField()),
                ('gameDuration', models.IntegerField()),
                ('matchDate', models.TextField()),
                ('matchTime', models.TextField()),
                ('initiatingPlayer', models.TextField(default=None)),
                ('acceptingPlayer', models.TextField(default=None)),
                ('scoreInitiatingPlayer', models.IntegerField()),
                ('scoreAcceptingPlayer', models.IntegerField()),
                ('longestStreakInitiatingPlayer', models.IntegerField()),
                ('longestStreakAcceptingPlayer', models.IntegerField()),
                ('longestBallRallyHits', models.IntegerField()),
                ('winner', models.TextField()),
                ('loser', models.TextField()),
                ('ballMissesTotal', models.IntegerField()),
                ('ballMissesInitiatingPlayer', models.IntegerField()),
                ('ballMissesAcceptingPlayer', models.IntegerField()),
                ('ballHitsTotal', models.IntegerField()),
                ('ballHitsInitiatingPlayer', models.IntegerField()),
                ('ballHitsAcceptingPlayer', models.IntegerField()),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pong.tournaments')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email_pk', models.TextField(primary_key=True, serialize=False)),
                ('isOnline', models.BooleanField(default=False)),
                ('isSearchingGame', models.BooleanField(default=False)),
                ('name', models.TextField()),
                ('inGameWith', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pong.users')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentUsersJunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pong.tournaments')),
                ('user_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pong.users')),
            ],
        ),
        migrations.CreateModel(
            name='GamesUsersJunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pong.games')),
                ('user_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pong.users')),
            ],
        ),
    ]
