# Generated by Django 5.0.3 on 2024-03-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoGameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameDuration', models.FloatField()),
                ('matchDate', models.CharField(max_length=30)),
                ('matchTime', models.CharField(max_length=30)),
                ('initiatingPlayer', models.CharField(max_length=30)),
                ('acceptingPlayer', models.CharField(max_length=30)),
                ('scoreInitiatingPlayer', models.IntegerField()),
                ('scoreAcceptingPlayer', models.IntegerField()),
                ('longestStreakInitiatingPlayer', models.IntegerField()),
                ('longestStreakAcceptingPlayer', models.IntegerField()),
                ('longestBallRallyHits', models.IntegerField()),
                ('winner', models.CharField(max_length=30)),
                ('loser', models.CharField(max_length=30)),
                ('ballMissesTotal', models.IntegerField()),
                ('ballMissesInitiatingPlayer', models.IntegerField()),
                ('ballMissesAcceptingPlayer', models.IntegerField()),
                ('ballHitsTotal', models.IntegerField()),
                ('ballHitsInitiatingPlayer', models.IntegerField()),
                ('ballHitsAcceptingPlayer', models.IntegerField()),
            ],
        ),
    ]
