# Generated by Django 5.0.3 on 2024-03-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_djangogamedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangogamedata',
            name='acceptingPlayer',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='djangogamedata',
            name='ballHitsAcceptingPlayer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='djangogamedata',
            name='ballHitsInitiatingPlayer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='djangogamedata',
            name='ballHitsTotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='djangogamedata',
            name='ballMissesAcceptingPlayer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='djangogamedata',
            name='ballMissesInitiatingPlayer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='djangogamedata',
            name='ballMissesTotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='djangogamedata',
            name='initiatingPlayer',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='djangogamedata',
            name='longestBallRallyHits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='djangogamedata',
            name='longestStreakAcceptingPlayer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='djangogamedata',
            name='longestStreakInitiatingPlayer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='djangogamedata',
            name='loser',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='djangogamedata',
            name='matchDate',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='djangogamedata',
            name='matchTime',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='djangogamedata',
            name='scoreAcceptingPlayer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='djangogamedata',
            name='scoreInitiatingPlayer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='djangogamedata',
            name='winner',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
