# Generated by Django 5.0.3 on 2024-03-18 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_playergamestats_users_delete_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameType', models.TextField()),
                ('gameDuration', models.IntegerField(default=0)),
                ('matchDate', models.DateField()),
                ('matchTime', models.TimeField()),
                ('longestBallRallyHits', models.IntegerField(default=0)),
                ('ballMissesTotal', models.IntegerField(default=0)),
                ('ballHitsTotal', models.IntegerField(default=0)),
                ('loser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_games', to='pong.users')),
                ('player1', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_stats_player1', to='pong.playergamestats')),
                ('player2', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_stats_player2', to='pong.playergamestats')),
                ('winner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to='pong.users')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pong.tournaments')),
            ],
        ),
    ]
