# Generated by Django 5.0.3 on 2024-03-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_alter_djangogamedata_acceptingplayer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangogamedata',
            name='gameDuration',
            field=models.FloatField(default=0.0),
        ),
    ]
