# Generated by Django 5.0.3 on 2024-03-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_alter_djangogamedata_gameduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangogamedata',
            name='gameDuration',
            field=models.IntegerField(default=0),
        ),
    ]
