# Generated by Django 5.0.3 on 2024-03-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_alter_djangogamedata_gameduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangogamedata',
            name='gameType',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
