# Generated by Django 5.0.3 on 2024-03-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0006_djangogamedata_gametype'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangogamedata',
            name='tournament_id_fk',
            field=models.IntegerField(default=-1),
        ),
    ]
